name: Docker Image Build

on:
  push:
    branches: [ develop, feature/* ]
  pull_request:
    branches: [ develop, feature/* ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Pull submodule
      run: |
        git submodule update --init --recursive
        git submodule update --recursive --remote
    
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile
